services:
  - type: web
    name: msme-backend
    env: node
    buildCommand: npm install && pip install pandas openpyxl xlrd
     apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000