# services:
#   - type: web
#     name: msme-backend
#     env: docker
#     dockerfilePath: backend/Dockerfile
#     dockerContext: backend
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: PORT
#         value: 10000


services:
  - type: web
    name: msme-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_PATH
        value: python3
      - key: GEMINI_MODEL_NAME
        value: gemini-2.5-flash